image: docker:25.0.3
variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
services:
  - docker:dind

stages:
  - deploy

deploy-frontend:
  stage: deploy
  image: quay.io/openshift/origin-cli:latest
  tags:
    - dev-container
  script:
    - echo "Checking contexts..."
    - kubectl config get-contexts
    - kubectl config use-context pcs-8/test-orientasi:ort-agent || echo "Context not found, trying local path..."
    - kubectl config use-context pcs-8/test-orientasi-react:ort-agent || echo "Still not found!"
    - cat $KUBECONFIG || echo "Kubeconfig file not found!"